title: Josef Fruehwald
email: josef.fruehwald@uky.edu
office: "1671 Patterson Office Tower"
baseurl: ""
url: "http://jofrhwld.github.io/"
twitter_username: jofrhwld
github_username:  jofrhwld
instagram_username:  jofrhwld

# Build settings
theme: minima
